### PR TITLE
Adding basic Failsafe support 

### LINKED ISSUE #30: Add Failsafe
There is another `Failure handling and resilience patterns for the JVM` - [Failsafe](https://github.com/jhalterman/failsafe), I would like to help to make a implementation based on it.

### PR DESCRIPTION
**Pull request by kubamarchwicki**
This PR intended to add [Failsafe](https://github.com/jhalterman/failsafe) support to Spring Cloud Circuitbreaker. This closes #30 

* [x] Creating failsafe module
* [x] Configurable `RetryPolicy` and `CircuitBreaker`
* [x] Add support for customizers

The Failsafe support is basic (similar to one based spring-retry template). Next step should include support for reactive extensions (with Async callbacks in Failsafe)

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
Please add some documentation

**Comment by kubamarchwicki** [comment]
Catched up with documentation.

**Comment by ryanjbaxter** [comment]
@kubamarchwicki we decided as a team that the best approach would be to create a separate module or project somewhere that adds this support.  As a team we don't want to be responsible for maintaining the implementation at the moment.  We did the same thing for the Sentinal implementation (which lives outside this project).

**Comment by kubamarchwicki** [comment]
Thank you @ryanjbaxter for feedback. I'll follow the path of Sentinal :-)

**Comment by ryanjbaxter** [comment]
@kubamarchwicki thanks!  Please let us know when you have an implementation we would happily list it in our docs!

**Pull request closed without merging**
